# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-03 02:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicly_traded_companies', '0002_auto_20171003_0001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='ipo_year',
            field=models.IntegerField(null=True),
        ),
    ]
