# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-21 03:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('publicly_traded_companies', '0003_auto_20171003_0207'),
    ]

    operations = [
        migrations.CreateModel(
            name='Industry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='company',
            name='ipo_year',
        ),
        migrations.AddField(
            model_name='company',
            name='address_line_1',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='address_line_2',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='business_summary',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='city',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='country',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='employee_count',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='fax_number',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='phone_number',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='state',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='website_url',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='zip_code',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='industry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='publicly_traded_companies.Industry'),
        ),
        migrations.AlterField(
            model_name='company',
            name='sector',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='publicly_traded_companies.Sector'),
        ),
    ]
