# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-21 03:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicly_traded_companies', '0004_auto_20171021_0305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='industry',
            name='name',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='sector',
            name='name',
            field=models.TextField(null=True),
        ),
    ]
